### ISSUE TITLE
annotation file

### ISSUE THREAD

**Issue by Frank-Wang-wow** [gtangg12/samesh#1]
I would like to express my sincere appreciation for the excellent work you have done. Would you please share the annotation file of your dataset or direct me to where I might access it? It would be an invaluable help to my work, and I would be extremely grateful for your support.

**Comment by gtangg12** [comment]
Hi, I've attached a link to the annotations. The file contains the videos displayed to the test subject for both experiments (SAMesh vs ShapeDiam and ablations on SAM2 input modalities) as well as the labels from AWS SageMaker Ground Truth.

https://drive.google.com/file/d/1UJMIdFZ1kUnV_ESm1j4z7fhzMRt-5kdh/view?usp=sharing

**Comment by Frank-Wang-wow** [comment]
Thank you for sharing the annotations and for your prompt reply. I have reviewed the file, but have some difficulty fully understanding it and I'm unsure how to utilize them. Would it be possible to provide the original 3D files, with annotations specifying the category of each point or mesh in the 3D model? This would greatly help in clarifying the structure and content of the annotations.
I appreciate your support and look forward to your response.
Best regards.



---Original---
From: "George ***@***.***&gt;
Date: Mon, Sep 16, 2024 06:08 AM
To: ***@***.***&gt;;
Cc: "Little ***@***.******@***.***&gt;;
Subject: Re: [gtangg12/samesh] annotation file (Issue #1)




 
Hi, I've attached a link to the annotations. The file contains the videos displayed to the test subject for both experiments (SAMesh vs ShapeDiam and ablations on SAM2 input modalities) as well as the labels from AWS SageMaker Ground Truth. Let me know if you have trouble accessing it.
 
https://drive.google.com/file/d/1UJMIdFZ1kUnV_ESm1j4z7fhzMRt-5kdh/view?usp=sharing

**Comment by gtangg12** [comment]
Hi, I currently do not have the multi view renders or segmented meshes, but you can reproduce them by running the code (see notebooks  for examples).

**Comment by gtangg12** [comment]
Closed since no follow up
