### ISSUE TITLE
Problem of Rendering

### ISSUE THREAD

**Issue by hkdsc** [gtangg12/samesh#3]
Hi! When I use default settings to run on some instances (such as jacket.glb), I find that there are some square holes on the rendering images. Do you know why? Thanks.
<img src="https://github.com/user-attachments/assets/c2d0edb9-f922-4929-948d-3cdb54a1c304" width="25%" height="25%"><img src="https://github.com/user-attachments/assets/70a11fab-24cd-497d-8bd2-d145a3a471f2" width="25%" height="25%"><img src="https://github.com/user-attachments/assets/7132755d-cabb-4264-9fa9-e64988cf6e12" width="25%" height="25%"><img src="https://github.com/user-attachments/assets/196f988d-1a4d-4d54-a788-804c57d2008c" width="25%" height="25%">

**Comment by gtangg12** [comment]
Hi, can you upload the mesh to https://3dviewer.net/ and check? It might be your OpenGL.

**Comment by hkdsc** [comment]
> Hi, can you upload the mesh to https://3dviewer.net/ and check? It might be your OpenGL or some other external config. Do you mind providing more details?

Oh, it was indeed a problem of my OpenGL or external config, and it worked after I changed the server.
